#!/bin/bash

(
    swift build -c release --arch arm64 --arch x86_64
    cd .build/apple/Products/Release
    rm -rf knup-universal.tar.xz knup-universal
    mkdir knup-universal
    cp kn knup-universal/kn
    cp knup knup-universal/knup
    tar -cJvf knup-universal.tar.xz knup-universal
    echo "write: knup-universal.tar.xz"
)
