#!/bin/bash

set -u

ohai "Updating knup..."

(
    cd "${NEXT_REPOSITORY}" >/dev/null || return
    
    quiet_progress=("--quiet")
    retry 5 "git" "fetch" "${quiet_progress[@]}" "--force" "origin"
    retry 5 "git" "fetch" "${quiet_progress[@]}" "--force" "--tags" "origin"

    LATEST_GIT_TAG="$("git" tag --list --sort="-version:refname" | head -n1)"
    if [[ -z "${LATEST_GIT_TAG}" ]]
    then
        abort "Failed to query latest kn Git tag."
    fi
    execute "git" "checkout" "--quiet" "--force" "-B" "stable" "${LATEST_GIT_TAG}"

    ohai "Coping knup to ${NEXT_PREFIX}/bin..."

    source "utils/make"
    
    eval "install_binary knup https://github.com/kainian/knup/releases/download/${LATEST_GIT_TAG}/knup-universal.tar.xz"
)
